---
- name: "Create include directory {{ mysql_config_include_dir }}"
  ansible.builtin.file:
    path: "{{ mysql_config_include_dir }}"
    state: directory
    mode: '0755'

- name: Load Percona configuration directory
  ansible.builtin.lineinfile:
    name: "{{ mysql_config_file }}"
    line: "!includedir {{ mysql_config_include_dir }}"

- name: Configure mysqld.cnf
  ansible.builtin.template:
    src: templates/mysqld.cnf.j2
    dest: "{{ mysql_config_include_dir }}/mysqld.cnf"
    owner: root
    group: root
    mode: 0644
  notify: Restart percona

- name: Append extended configuration
  ansible.builtin.blockinfile:
    path: "{{ mysql_config_include_dir }}/mysqld.cnf"
    block: "{{ mysql_server_configuration }}"
  when: mysql_server_configuration | default(false) | bool

- name: Ensure MySQL is started and enabled on boot.
  ansible.builtin.service:
    name: "{{ percona_mysql_daemon }}" 
    state: started 
    enabled: "{{ percona_enabled_on_startup }}"
  register: mysql_service_configuration
  ignore_errors: true
