---
- name: Set new root password
  ansible.builtin.shell: |
    bash | set -o pipefail
    bash | mysql --connect-expired-password -e "ALTER USER '{{ percona_root_user }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ percona_root_password }}';"
  changed_when: false
  failed_when: false

- name: Create .mycnf file for root user
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.my.cnf"
    mode: 0644
    content: |
      [client]
      user={{ percona_root_user }}
      password={{ percona_root_password }}
  notify: restart percona