---
- name: Get temporary Percona root password.
  ansible.builtin.shell: |
    set -o pipefail
    grep 'temporary password' '{{ mysql_log_error }}' | awk '{print $NF}' | tail -n 1
  register: "_percona_root_temp_password"
  changed_when: false

- name: Get user home directory.
  ansible.builtin.shell: "echo $HOME"
  register: user_home_directory
  changed_when: false

- name: Create .mycnf file for root user
  ansible.builtin.copy:
    dest: "{{ user_home_directory.stdout }}/.my.cnf"
    mode: 0644
    content: |
      [client]
      user=root
      password={{ _percona_root_temp_password.stdout }}

- name: Set new root password
  ansible.builtin.shell: >
    mysql --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ percona_root_password }}';"
  changed_when: false

- name: Change Percona root password in .my.cnf.
  lineinfile:
    path: "{{ user_home_directory.stdout }}/.my.cnf"
    state: present
    regexp: '^.?password=*'
    line: "password={{ percona_root_password }}"