---
- name: Get temporary Percona root password.
  ansible.builtin.shell: |
    set -o pipefail
    grep 'temporary password' '{{ mysql_log_error }}' | awk '{print $NF}' | tail -n 1
  register: __percona_root_temp_password
  changed_when: false

- name: Create .mycnf file for root user
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.my.cnf"
    mode: 0644
    content: |
      [client]
      user={{ percona_root_user | quote }}
      password={{ __percona_root_temp_password.stdout | quote }}
  notify: Restart percona

- name: Set new root password
  ansible.builtin.shell: >
    mysql --connect-expired-password -e "ALTER USER '{{ percona_root_user }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ percona_root_password }}';"
  changed_when: false
  failed_when: false

- name: Change root password in .my.cnf.
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.my.cnf"
    state: present
    regexp: '^.?password=*'
    line: "password={{ percona_root_password | quote }}"
  notify: Restart percona