---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ percona_required_packages }}"
  register: deb_percona_install_required_packages

- name: Calculate Debian lsb_release
  ansible.builtin.shell: >
    lsb_release -sc
  register: lsb_release
  check_mode: no
  changed_when: false
  failed_when: false

- name: Ensure Percona repositories are installed
  ansible.builtin.apt:
    deb: "{{ percona_repo_baseurl }}/{{ percona_repo_release }}.{{ lsb_release.stdout }}_all.deb"

- name: Setup Percona release
  ansible.builtin.shell: |
    bash | set -o pipefail
    bash | percona-release setup ps{{ percona_version }}
  changed_when: false
  failed_when: false

- name: Ensure Percona packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: 
    - "{{ percona_packages }}"
  register: deb_percona_install_required_packages
