---
name: Ansible Role Percona MySQL Server
'on':
  push:

jobs:

  lint:
    name: Linting ansible role bmeme.percona_server
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v3
      -
        name: Run ansible-lint
        uses: ansible/ansible-lint@main

  test:
    name: Testing bmeme.percona_server role 8.x and 9.x Ansible version
    runs-on: ubuntu-24.04
    needs: [lint]
    strategy:
      matrix:
        ansible:
          - "8.7.0"
          - "9.13.0"
        distro:
          - "rockylinux:8.10-2.15"
          - "rockylinux:9.4-2.15"
          - "rockylinux:9.4-2.16"
          - "ubuntu:22.04-2.15"
          - "ubuntu:22.04-2.16"
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v3
      -
        name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      -
        # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
        name: Disable AppArmor
        run: |
          set -x
          sudo apt-get install apparmor-profiles
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        if: startsWith(matrix.distro, 'ubuntu')
      -
        name: Install requirements
        run: pip install ansible==${{ matrix.ansible }} molecule molecule-plugins[docker]
      -
        name: Run Molecule test
        run: molecule test -d docker --all
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
