---
name: Ansible Role Percona MySQL Server
'on':
  push:

jobs:

  lint:
    name: Linting ansible role bmeme.percona_server
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v3
      -
        name: Run ansible-lint
        uses: ansible/ansible-lint@main

  test:
    name: Testing ansible role bmeme.percona_server
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        scenario:
          - "default"
          - "default80"
        distro: 
          - "rockylinux:8.7-2.11"
          - "rockylinux:8.8-2.11"
          - "rockylinux:8.9-2.11"
          - "rockylinux:9.3-2.15"
          - "ubuntu:20.04-2.11"
          - "ubuntu:20.04-2.13"
          - "ubuntu:22.04-2.13"
          - "ubuntu:22.04-2.17"
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v3
      -
        # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
        name: Disable AppArmor
        run: |
          set -x
          sudo apt-get install apparmor-profiles
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        if: startsWith(matrix.distro, 'ubuntu')
      -
        name: Molecule test
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug
          molecule_args: -d docker --scenario-name ${{ matrix.scenario }}
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
