---
name: Ansible Role Percona MySQL Server
'on':
  release:
    types: ['created']

jobs:

  release:
    name: Galaxy Role Importer
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v4
      - 
        name: Release on galaxy
        uses: ansible-actions/ansible-galaxy-action@v1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}